
[General]
	#Whether Technoflesh creatures gain buffs as game time goes by, Default: true
	TechnoFleshBuff = true
	#If 'TechnoFleshBuff' is set to true, whether it gains buffs via minecraft days instead of game time, Default: false
	TechnoFleshBuffDayTime = false
	#If set above 0 and 'TechnoFleshBuff' is set to true, Technoflesh creatures will always be buffed as though the 'TechnoFleshBuffDayTime' is enabled and the input amount of days have passed, set to 0 to disable, Default: 0
	#Range: > 0
	FixedAdaptationStage = 0
	#Whether Meteor Showers can occur, Default: true
	MeteorShower = true
	#If 'MeteorShower' is enabled, whether Meteor Showers make flashes, Default: true
	MeteorShowerFlash = true
	#If 'MeteorShower' is enabled, Meteor Showers will occur ever defined days, Default: 15
	#Range: > 1
	MeteorShowerDays = 15
	#If 'MeteorShower' is enabled, how many seconds do Meteor Showers lasts, Default: 180
	#Range: 1 ~ 550
	MeteorShowerDuration = 180
	#Players camera can shake. Default: true
	CameraShake = true

["Mob Spawn"]

	["Mob Spawn"."Heart of Decay"]
		#Spawn Weight for Heart of Decay, Default: 15
		#Range: > 0
		HoDSpawnWeight = 15
		#Spawn minimum group count for Heart of Decay, Default: 1
		#Range: > 1
		HoDSpawnMinCount = 1
		#Spawn maximum group count for Heart of Decay, must be equal or higher than min count, Default: 3
		#Range: > 1
		HoDSpawnMaxCount = 3
		#How many days until Heart of Decay can spawn, set to -1 to disable, Default: 0
		#Range: > -1
		HoDDaySpawn = 0

	["Mob Spawn"."Ex Reaper"]
		#Spawn Weight for Ex Reaper, Default: 15
		#Range: > 0
		ExReaperSpawnWeight = 15
		#Spawn minimum group count for Ex Reaper, Default: 1
		#Range: > 1
		ExReaperSpawnMinCount = 1
		#Spawn maximum group count for Ex Reaper, must be equal or higher than min count, Default: 2
		#Range: > 1
		ExReaperSpawnMaxCount = 2
		#How many days until Ex Reaper can spawn, set to -1 to disable, Default: 15
		#Range: > -1
		ExReaperDaySpawn = 8

	["Mob Spawn"."Flesh Maiden"]
		#Spawn Weight for Flesh Maiden, Default: 15
		#Range: > 0
		FleshMaidenSpawnWeight = 15
		#Spawn minimum group count for Flesh Maiden, Default: 1
		#Range: > 1
		FleshMaidenSpawnMinCount = 1
		#Spawn maximum group count for Flesh Maiden, must be equal or higher than min count, Default: 2
		#Range: > 1
		FleshMaidenSpawnMaxCount = 2
		#How many days until Flesh Maiden can spawn, set to -1 to disable, Default: 15
		#Range: > -1
		FleshMaidenDaySpawn = 8

	["Mob Spawn".Hematoma]
		#Spawn Weight for Hematoma, Default: 19
		#Range: > 0
		HematomaSpawnWeight = 19
		#Spawn minimum group count for Hematoma, Default: 1
		#Range: > 1
		HematomaSpawnMinCount = 1
		#Spawn maximum group count for Hematoma, must be equal or higher than min count, Default: 2
		#Range: > 1
		HematomaSpawnMaxCount = 2
		#How many days until Hematoma can spawn, set to -1 to disable, Default: 15
		#Range: > -1
		HematomaDaySpawn = 8

	["Mob Spawn"."Blood Spreader"]
		#Spawn Weight for Blood Spreader, Default: 15
		#Range: > 0
		BloodSpreaderSpawnWeight = 15
		#Spawn minimum group count for Blood Spreader, Default: 1
		#Range: > 1
		BloodSpreaderSpawnMinCount = 1
		#Spawn maximum group count for Blood Spreader, must be equal or higher than min count, Default: 3
		#Range: > 1
		BloodSpreaderSpawnMaxCount = 3
		#How many days until Blood Spreader can spawn, set to -1 to disable, Default: 15
		#Range: > -1
		BloodSpreaderDaySpawn = 8

	["Mob Spawn".Prowler]
		#Spawn Weight for Prowler, Default: 10
		#Range: > 0
		ProwlerSpawnWeight = 10
		#Spawn minimum group count for Prowler, Default: 1
		#Range: > 1
		ProwlerSpawnMinCount = 1
		#Spawn maximum group count for Prowler, must be equal or higher than min count, Default: 1
		#Range: > 1
		ProwlerSpawnMaxCount = 1
		#How many days until Prowler can spawn, set to -1 to disable, Default: 15
		#Range: > -1
		ProwlerDaySpawn = 8

	["Mob Spawn".Carcass]
		#Spawn Weight for Carcass, Default: 10
		#Range: > 0
		CarcassSpawnWeight = 10
		#Spawn minimum group count for Carcass, Default: 1
		#Range: > 1
		CarcassSpawnMinCount = 1
		#Spawn maximum group count for Carcass, must be equal or higher than min count, Default: 1
		#Range: > 1
		CarcassSpawnMaxCount = 1
		#How many days until Carcass can spawn, set to -1 to disable, Default: 15
		#Range: > -1
		CarcassDaySpawn = 8

