
["Growling Man Config"]
	#a random number is generated between min and max for the spawn time, the spawn numbers are in seconds so set how many seconds you want it to take for him to spawn on min and max, WARNING do not make max time lower than min time otherwise it will cause bugs or crash the game
	"GM Spawntime Min" = 60.0
	#a random number is generated between min and max for the spawn time, the spawn numbers are in seconds so set how many seconds you want it to take for him to spawn on min and max, WARNING do not make max time lower than min time otherwise it will cause bugs or crash the game
	"GM Spawntime Max" = 240.0
	#if you want a higher chance of him spawning set the spawn chance to a lower number, if you want a lower chance for him to spawn set the spawn chance to a higher number, WARNING do not set this number below 1 otherwise it may bug or crash the game
	"GM Spawn Chance" = 1.0
	"Regenerate Blocks If Broken By The Entity" = false
	#a random number is generated between min and max for the chase time, the chase numbers are in minutes so set how many minutes you want it to take for him to disappear on min and max, WARNING do not make max time lower than min time otherwise it will cause bugs or crash the game
	"GM Chase Time Min" = 1.0
	#a random number is generated between min and max for the chase time, the chase numbers are in minutes so set how many minutes you want it to take for him to disappear on min and max, WARNING do not make max time lower than min time otherwise it will cause bugs or crash the game
	"GM Chase Time Max" = 2.0
	"Don't Spawn GM On First Day" = false
	#a random number is generated between 20 and the set config number for the spawn distance, spawn distance is in blocks so 100 would be 100 blocks away etc, WARNING do not set spawn distance below 20 otherwise it will cause bugs or crash the game
	"GM Max Spawn Distance" = 70.0
	#max for animal kills is 20 and min is 3, if you set a number lower or higher then it will default to the closest max or min amount
	"Amount Of Quick Animal Kills Needed To Get Marked" = 10.0

