#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Apr 17 22:44:47 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=10
shaderPack=Spooklementary_v2.0.4.zip
enableShaders=true
