// priority: 0

// Visit the wiki for more info - https://kubejs.com/

JEIEvents.hideItems(event => {
    event.hide('survival_instinct:chicken_head_helmet')
    event.hide('survival_instinct:motorcycle_helmet')
    event.hide('survival_instinct:gas_mask_helmet')
    event.hide('survival_instinct:night_vision_goggles_helmet')
    event.hide('survival_instinct:desert_hunter_helmet')
    event.hide('survival_instinct:desert_rockie_armor_helmet')
    event.hide('survival_instinct:desert_rockie_armor_chestplate')
    event.hide('survival_instinct:desert_rockie_armor_leggings')
    event.hide('survival_instinct:desert_rockie_armor_boots')
    event.hide('survival_instinct:green_hunter_helmet')
    event.hide('survival_instinct:green_rockie_armor_helmet')
    event.hide('survival_instinct:green_rockie_armor_chestplate')
    event.hide('survival_instinct:green_rockie_armor_leggings')
    event.hide('survival_instinct:green_rockie_armor_boots')
    event.hide('survival_instinct:black_hunter_helmet')
    event.hide('survival_instinct:black_rockie_armor_helmet')
    event.hide('survival_instinct:black_rockie_armor_chestplate')
    event.hide('survival_instinct:black_rockie_armor_leggings')
    event.hide('survival_instinct:black_rockie_armor_boots')
    event.hide('survival_instinct:military_helmet')
    event.hide('survival_instinct:military_chestplate')
    event.hide('survival_instinct:military_leggings')
    event.hide('survival_instinct:military_boots')
    event.hide('survival_instinct:guillie_helmet')
    event.hide('survival_instinct:guillie_chestplate')
    event.hide('survival_instinct:guillie_leggings')
    event.hide('survival_instinct:guillie_boots')
    event.hide('survival_instinct:spruce_guillie_helmet')
    event.hide('survival_instinct:spruce_guillie_chestplate')
    event.hide('survival_instinct:spruce_guillie_leggings')
    event.hide('survival_instinct:spruce_guillie_boots')
    event.hide('survival_instinct:artic_guillie_helmet')
    event.hide('survival_instinct:artic_guillie_chestplate')
    event.hide('survival_instinct:artic_guillie_leggings')
    event.hide('survival_instinct:artic_guillie_boots')
    event.hide('survival_instinct:hazmat_helmet')
    event.hide('survival_instinct:hazmat_chestplate')
    event.hide('survival_instinct:hazmat_leggings')
    event.hide('survival_instinct:hazmat_boots')
    event.hide('survival_instinct:fire_fighter_helmet')
    event.hide('survival_instinct:fire_fighter_chestplate')
    event.hide('survival_instinct:fire_fighter_leggings')
    event.hide('survival_instinct:fire_fighter_boots')
    event.hide('survival_instinct:police_helmet')
    event.hide('survival_instinct:police_chestplate')
    event.hide('survival_instinct:police_leggings')
    event.hide('survival_instinct:police_boots')
    event.hide('survival_instinct:green_juggernaut_helmet')
    event.hide('survival_instinct:green_juggernaut_chestplate')
    event.hide('survival_instinct:green_juggernaut_leggings')
    event.hide('survival_instinct:green_juggernaut_boots')
    event.hide('survival_instinct:desert_juggernaut_helmet')
    event.hide('survival_instinct:desert_juggernaut_chestplate')
    event.hide('survival_instinct:desert_juggernaut_leggings')
    event.hide('survival_instinct:desert_juggernaut_boots')
    event.hide('survival_instinct:black_juggernaut_helmet')
    event.hide('survival_instinct:black_juggernaut_chestplate')
    event.hide('survival_instinct:black_juggernaut_leggings')
    event.hide('survival_instinct:black_juggernaut_boots')
    event.hide('survival_instinct:lance_wit_screwdriver')
})

console.info('Hello, World! (Loaded client scripts)')

